### ISSUE TITLE
Creds are open

### ISSUE THREAD

**Issue by rajkumaar23** [cyberShaw/dank-doggo#1]
Rebase your git history and remove the creds which can be viewed before https://github.com/cyberShaw/dank-doggo/commit/0bb1e2acb99afe6159773ca080b39345fc697c4d

**Comment by cyberShaw** [comment]
Thanks for pointing it out! I'll fix it asap!

**Comment by cyberShaw** [comment]
> Rebase your git history and remove the creds which can be viewed before [0bb1e2a](https://github.com/cyberShaw/dank-doggo/commit/0bb1e2acb99afe6159773ca080b39345fc697c4d)

@rajkumaar23  Since my credentials were added to the first commit, I couldn't use ```git filter-branch``` to remove it.
I used ```git update-ref -d HEAD``` and fixed it.
